pipeline {
    agent any

    tools {
        // Make sure Gradle is installed in Jenkins global tools
        gradle 'Gradle-9.3.1'
        jdk 'JDK-21'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Test') {
            steps {
                sh './gradlew clean build test'
            }
        }

        stage('Archive Artifact') {
            steps {
                // Archive the JAR(s) generated by Gradle
                archiveArtifacts artifacts: 'build/libs/*.jar', fingerprint: true
            }
        }
    }

    post {
        always {
            junit '**/build/test-results/test/*.xml' // show test results in Jenkins
        }
    }
}
